// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGWtlBBmdpVQ9TfUDkPz4VqfxBdoxT1fY',
    appId: '1:736451319430:web:dc9d40a403c182b58ee307',
    messagingSenderId: '736451319430',
    projectId: 'notes-app-4f1c0',
    storageBucket: 'notes-app-4f1c0.firebasestorage.app',
    authDomain: 'notes-app-4f1c0.firebaseapp.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGWtlBBmdpVQ9TfUDkPz4VqfxBdoxT1fY',
    appId: '1:736451319430:android:dc9d40a403c182b58ee307',
    messagingSenderId: '736451319430',
    projectId: 'notes-app-4f1c0',
    storageBucket: 'notes-app-4f1c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGWtlBBmdpVQ9TfUDkPz4VqfxBdoxT1fY',
    appId: '1:736451319430:ios:dc9d40a403c182b58ee307',
    messagingSenderId: '736451319430',
    projectId: 'notes-app-4f1c0',
    storageBucket: 'notes-app-4f1c0.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGWtlBBmdpVQ9TfUDkPz4VqfxBdoxT1fY',
    appId: '1:736451319430:ios:dc9d40a403c182b58ee307',
    messagingSenderId: '736451319430',
    projectId: 'notes-app-4f1c0',
    storageBucket: 'notes-app-4f1c0.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGWtlBBmdpVQ9TfUDkPz4VqfxBdoxT1fY',
    appId: '1:736451319430:web:dc9d40a403c182b58ee307',
    messagingSenderId: '736451319430',
    projectId: 'notes-app-4f1c0',
    storageBucket: 'notes-app-4f1c0.firebasestorage.app',
    authDomain: 'notes-app-4f1c0.firebaseapp.com',
  );
}
